### PR TITLE
Add `io` to `BoardOptions`

### PR DESCRIPTION
**Pull request by urish**
for specifying a custom i/o driver, such as raspi-io

### CODE REVIEW

**Comment by shyiko** [comment]
@urish Thank you!

**Comment by urish** [comment]
Great! I am going to use it for a demo in ng-conf on Thursday, now the demo is going to be much more neat :)

**Comment by shyiko** [comment]
Awesome. I'm glad I decided to take a look a PRs today and not on Wednesday as I usually do :) Best of luck, man! :beers:

**Comment by urish** [comment]
Thank you! 

Is there any way to install the updated version through `typings`? or only through npm ?

**Comment by shyiko** [comment]
It's available through npm. I use [tsdm](https://github.com/shyiko/tsdm) instead of `typings` and so I'm not sure whether it can be installed "as is" using the latter.

**Pull request merged**
